import {
    InputState,
    RelationKey,
    EventKey,
    ImportanceKey,
    NoticeKey,
    ToneKey,
    ClosenessKey,
    ExcuseTemplate,
} from './types';

export const initialForm: InputState = {
    relationship: '',
    relationshipCustom: '',
    closeness: '',
    event: '',
    eventCustom: '',
    importance: '',
    notice: '',
    tone: '',
    previousExcuses: [],
    previousExcuseInput: '',
    additionalContext: '',
};

export const ALL_RELATIONSHIPS: RelationKey[] = ['Friend', 'Best Friend', 'Family', 'Date', 'Coworker', 'Boss', 'Client'];
export const ALL_EVENTS: EventKey[] = ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Birthday', 'Party', 'Meeting', 'Trip', 'Interview'];
export const ALL_IMPORTANCE: ImportanceKey[] = ['Casual', 'Planned', 'Important', 'Very Important'];
export const ALL_NOTICE: NoticeKey[] = ['15 minutes', '1 hour', 'Today', 'Tomorrow', 'A few days', 'A week'];
export const ALL_TONE: ToneKey[] = ['Casual', 'Professional', 'Formal', 'Very apologetic'];

export const excuseTemplates: ExcuseTemplate[] = [
    // --- WORK & PROFESSIONAL ---
    {
        id: 'work-deadline',
        category: 'workload',
        variants: [
            "A massive surprise deadline just dropped on my desk. I'm going to be stuck working tonight.",
            "I'm swamped with an upcoming deadline and have to stay heads-down to finish it.",
            "Work piled up faster than expected, I need to stay late and won't be able to make {{event}}.",
            "I've got a deadline tomorrow that I'm way behind on. I have to cancel.",
            "My team is scrambling to meet a deadline, so I'm grounded at my desk.",
        ],
        relationshipSuitability: ['Coworker', 'Boss', 'Friend', 'Best Friend', 'Family', 'Date'],
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.82,
        explanation: 'A classic, universally understood excuse. Everyone hates surprise deadlines.',
        keywords: ['deadline', 'swamped', 'work', 'desk', 'late'],
    },
    {
        id: 'work-server-down',
        category: 'professional-urgent',
        variants: [
            "Our servers just went down and it's all-hands-on-deck to fix it.",
            "We have a critical production incident at work. I'm stuck firefighting.",
            "The site just crashed and I'm on call. I can't step away right now.",
            "There's a massive outage at work and I have to help resolve it immediately.",
            "Emergency at work—our main system is down. I'll be stuck here troubleshooting.",
        ],
        relationshipSuitability: ['Boss', 'Client', 'Coworker', 'Friend', 'Best Friend', 'Date'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Party', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Planned', 'Important', 'Very Important'],
        toneSuitability: ['Professional', 'Formal', 'Very apologetic'],
        baseConfidence: 0.88,
        explanation: 'Very strong for tech/corporate roles. Unquestionable urgency.',
        keywords: ['server', 'down', 'outage', 'production', 'incident', 'firefighting'],
    },
    {
        id: 'client-emergency',
        category: 'professional-urgent',
        variants: [
            "One of our biggest clients just called with an absolute emergency.",
            "A client issue needs my immediate attention, I can't leave the office.",
            "I have to jump on a crisis call with a client right now. So sorry!",
            "Things just blew up with a client account and I'm the point person to fix it.",
            "Client escalation just happened. I'm going to be tied up dealing with this.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Best Friend', 'Date', 'Family'],
        eventSuitability: ['Lunch', 'Dinner', 'Coffee', 'Movie', 'Party', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Important', 'Very Important', 'Planned'],
        toneSuitability: ['Professional', 'Formal', 'Very apologetic'],
        baseConfidence: 0.87,
        explanation: 'Strong professional boundary. People rarely question client emergencies.',
        keywords: ['client', 'escalation', 'emergency', 'account', 'crisis'],
    },
    {
        id: 'meeting-ran-over',
        category: 'scheduling',
        variants: [
            "My last meeting is running way over time and I can't gracefully exit.",
            "I'm stuck in a meeting that just won't end. I'm going to miss {{event}}.",
            "This call is dragging on forever and I can't drop off.",
            "We're stuck in negotiations/discussions and it's running severely late.",
            "A crucial meeting ran over by an hour and derailed my whole schedule.",
        ],
        relationshipSuitability: ['Coworker', 'Boss', 'Client', 'Friend', 'Best Friend', 'Date'],
        eventSuitability: ['Coffee', 'Lunch', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Professional', 'Casual', 'Very apologetic'],
        baseConfidence: 0.80,
        explanation: 'Perfect for short-notice cancellations of daytime/afternoon events.',
        keywords: ['meeting', 'ran over', 'late', 'call', 'dragging'],
    },
    {
        id: 'boss-needs-me',
        category: 'professional-urgent',
        variants: [
            "My boss just pulled me into something urgent that I can't say no to.",
            "Leadership just dropped a priority project on me that needs to be done tonight.",
            "My manager asked me to stay late for an emergency review.",
            "The CEO/VP needs this report ASAP, so my evening is shot.",
            "Got cornered by my boss on my way out. I'm trapped for the foreseeable future.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Family', 'Coworker'],
        eventSuitability: ['Dinner', 'Movie', 'Party', 'Coffee', 'Lunch'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.79,
        explanation: 'Shifts the blame entirely to an authority figure.',
        keywords: ['boss', 'manager', 'ceo', 'leadership', 'urgent'],
    },
    {
        id: 'networking-event',
        category: 'professional-urgent',
        variants: [
            "I got last-minute roped into a mandatory networking event for work.",
            "My company is forcing us to attend a corporate dinner tonight.",
            "I have an unavoidable work function that I completely forgot about.",
            "There's an industry mixer tonight that my boss insists I attend.",
            "I have to schmooze at a work event tonight. Wish I could get out of it.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date'],
        eventSuitability: ['Dinner', 'Party', 'Movie'],
        noticeSuitability: ['Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.73,
        explanation: 'Good for evening events when you need a professional excuse.',
        keywords: ['networking', 'corporate', 'mixer', 'event', 'function'],
    },

    // --- HEALTH & MEDICAL ---
    {
        id: 'health-migraine',
        category: 'illness',
        variants: [
            "I've got a blinding migraine coming on and need to lie down in a dark room.",
            "A really bad headache just hit me out of nowhere. I can't stare at lights or screens.",
            "I suffer from migraines and one just triggered. I'm completely out of commission.",
            "My head is pounding so hard I can barely see. I have to cancel.",
            "Migraine aura just started. I need to take my meds and sleep it off.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important', 'Very Important'],
        toneSuitability: ALL_TONE,
        baseConfidence: 0.89,
        explanation: 'Migraines are sudden, debilitating, and unquestionable.',
        keywords: ['migraine', 'headache', 'pounding', 'dark room', 'aura'],
    },
    {
        id: 'health-food-poisoning',
        category: 'illness',
        variants: [
            "I think I got food poisoning from lunch. I cannot leave my bathroom.",
            "Something I ate is violently disagreeing with me.",
            "I am incredibly sick to my stomach right now. Definitely food poisoning.",
            "Stomach bug or food poisoning just hit me like a truck.",
            "I'm glued to the toilet right now. It's bad. I can't make it.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Boss', 'Coworker', 'Date'],
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important', 'Very Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.92,
        explanation: 'Nobody wants you around if you have food poisoning. Guaranteed cancellation.',
        keywords: ['food poisoning', 'stomach', 'sick', 'toilet', 'bathroom'],
    },
    {
        id: 'health-covid-scare',
        category: 'illness',
        variants: [
            "I woke up with a scratchy throat and fever. I should isolate just in case.",
            "Someone I was with yesterday just tested positive for COVID/flu.",
            "I'm showing symptoms of something contagious and don't want to risk exposing anyone.",
            "I'm waiting on test results for a bug going around. Better safe than sorry.",
            "Feeling super under the weather and feverish. I'm going to quarantine.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.88,
        explanation: 'Highly responsible excuse. It turns cancelling into a public service.',
        keywords: ['covid', 'fever', 'contagious', 'symptoms', 'isolate', 'expose'],
    },
    {
        id: 'health-back-pain',
        category: 'illness',
        variants: [
            "I completely threw my back out this morning. I can barely walk.",
            "I tweaked my back at the gym and it's spasming badly.",
            "My sciatica flared up terribly today, I need to stay flat on the floor.",
            "I bent over weirdly and my back just locked up.",
            "Severe lower back pain just hit me. I'm practically immobilized.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Trip', 'Coffee', 'Lunch'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.81,
        explanation: 'Very relatable physical ailment that prevents sitting at restaurants/movies.',
        keywords: ['back', 'threw out', 'spasm', 'locked up', 'sciatica'],
    },
    {
        id: 'health-allergies',
        category: 'illness',
        variants: [
            "I'm having a severe allergic reaction to something and need to take Benadryl.",
            "My allergies are absolutely out of control today, I can't stop sneezing and my eyes are swollen.",
            "I broke out in hives out of nowhere and need to monitor it.",
            "Seasonal allergies hit me so hard I look and feel terrible.",
            "I took some allergy meds that knocked me completely out.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Party'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.75,
        explanation: 'Good for casual events where you just don’t want to be seen feeling groggy.',
        keywords: ['allergy', 'allergic', 'hives', 'benadryl', 'swollen'],
    },
    {
        id: 'health-mental-day',
        category: 'personal-space',
        variants: [
            "I'm having a really bad mental health day and need to just shut off the world.",
            "I'm completely burnt out and running on empty. I need to take tonight for self-care.",
            "My anxiety is spiking today and I don't think I can handle a social setting.",
            "I'm emotionally exhausted and just need to rot in bed tonight. I'm sorry.",
            "I hit a wall today mentally. I need to rest and reset.",
        ],
        relationshipSuitability: ['Best Friend', 'Friend', 'Family'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Party'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.85,
        explanation: 'Honest and vulnerable. Only use with close friends/family who understand.',
        keywords: ['mental', 'anxiety', 'burnt out', 'exhausted', 'bed'],
    },
    {
        id: 'health-dental-emergency',
        category: 'illness',
        variants: [
            "I chipped a tooth and have to rush to an emergency dentist.",
            "I'm in agonizing tooth pain suddenly and got a last-minute dental appointment.",
            "A crown just fell out of my mouth. I have to go get it fixed immediately.",
            "My wisdom teeth are flaring up and the pain is unbearable.",
            "Emergency dental situation. My face is swollen and I can't talk or eat.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Formal', 'Very apologetic', 'Casual'],
        baseConfidence: 0.89,
        explanation: 'Specific, urgent, and usually gets a lot of sympathy.',
        keywords: ['tooth', 'dental', 'dentist', 'crown', 'pain'],
    },

    // --- HOME & LOGISTICS ---
    {
        id: 'home-pipe-burst',
        category: 'logistics',
        variants: [
            "A pipe just burst in my apartment/house and there's water everywhere.",
            "My kitchen is flooding. I'm waiting for the emergency plumber.",
            "Major plumbing emergency at my place. I'm frantically soaking up water.",
            "The ceiling is leaking profusely. I have to deal with the landlord/plumber.",
            "Water heater just exploded. It's a disaster over here.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Formal', 'Very apologetic', 'Casual'],
        baseConfidence: 0.90,
        explanation: 'A catastrophic event that guarantees you cannot leave the house.',
        keywords: ['pipe', 'burst', 'plumber', 'water', 'flooding', 'leak'],
    },
    {
        id: 'home-locked-out',
        category: 'logistics',
        variants: [
            "I managed to lock myself out of my house and am waiting for a locksmith.",
            "Lost my keys and I'm stranded outside my apartment.",
            "My smart lock battery died and the physical key is inside. Waiting on maintenance.",
            "Locked my keys inside. The locksmith says it'll be a 2 hour wait.",
            "I can't get into my house. Currently stranded in the hallway waiting for a spare.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Dinner', 'Party', 'Meeting', 'Movie', 'Coffee'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic', 'Professional'],
        baseConfidence: 0.83,
        explanation: 'Highly believable mistake that temporarily ruins your mobility.',
        keywords: ['locked out', 'keys', 'locksmith', 'stranded', 'door'],
    },
    {
        id: 'home-appliance-fire',
        category: 'logistics',
        variants: [
            "My oven caught fire and the fire department is here checking the vents.",
            "Small electrical fire in my kitchen. Everyone is safe but it's a huge mess.",
            "My microwave started smoking heavily and set off all the alarms.",
            "We had a scary smoke/fire situation at the house. Dealing with the aftermath.",
            "Fire alarm won't stop going off and the fire department is assessing the building.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Formal', 'Very apologetic', 'Casual'],
        baseConfidence: 0.85,
        explanation: 'Extreme, but very effective for getting out of literally anything.',
        keywords: ['fire', 'smoke', 'alarm', 'department', 'kitchen'],
    },
    {
        id: 'home-delivery',
        category: 'logistics',
        variants: [
            "I have a highly valuable package requiring a signature and the window is 12-8.",
            "My furniture delivery is delayed and I have to stay home to let them in.",
            "The repair guy gave me an 8-hour window and finally said he's on his way.",
            "I'm trapped waiting for a contractor who was supposed to be here 3 hours ago.",
            "A massive freight delivery requires me to be physically present right now.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Family', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Party'],
        noticeSuitability: ['1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.77,
        explanation: 'Relatable adult problem. Everyone hates delivery windows.',
        keywords: ['delivery', 'signature', 'window', 'repair', 'contractor'],
    },
    {
        id: 'home-break-in',
        category: 'logistics',
        variants: [
            "My house got broken into (or attempted). I'm dealing with the police right now.",
            "Someone smashed my car window/apartment window. Waiting for the cops.",
            "Major security issue at my building, police are taking statements.",
            "My garage was burglarized and I'm currently filing a report.",
            "Got a notification from my security system and had to rush home.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.94,
        explanation: 'Only use in extreme cases. Unquestionable, but causes concern.',
        keywords: ['police', 'broken into', 'cops', 'security', 'burglarized'],
    },

    // --- FAMILY & PETS ---
    {
        id: 'family-childcare',
        category: 'family',
        variants: [
            "My babysitter cancelled at the absolute last minute.",
            "Daycare called and my kid is sick, I have to go pick them up immediately.",
            "Childcare fell through. I have no one to watch the kids tonight.",
            "My partner is stuck at work so I have to take over parent duty tonight.",
            "Kid has a sudden fever, we are in lockdown mode at home.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.89,
        explanation: 'For parents only. The ultimate, untouchable excuse.',
        keywords: ['babysitter', 'kid', 'childcare', 'daycare', 'parent'],
    },
    {
        id: 'family-eldercare',
        category: 'family',
        variants: [
            "My elderly parent had a fall and I need to go help them right now.",
            "My mom/dad is having a health scare, heading to their place to check in.",
            "An aging relative needs urgent assistance and I'm the only one nearby.",
            "Family caregiving duties just popped up unexpectedly.",
            "I have to take my grandparent to the ER just to be safe.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.91,
        explanation: 'Very sympathetic excuse. People will immediately tell you to go.',
        keywords: ['parent', 'elderly', 'fall', 'grandparent', 'caregiving'],
    },
    {
        id: 'pet-emergency',
        category: 'family',
        variants: [
            "My dog/cat is vomiting everywhere and I need to rush them to the emergency vet.",
            "My pet swallowed something toxic, heading to the animal hospital.",
            "My dog got out and I'm frantically searching the neighborhood.",
            "My cat got injured and I need to stay home to monitor them.",
            "Pet emergency. Very stressed, can't make it to {{event}}.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.88,
        explanation: 'People love pets. A pet emergency is treated like a human emergency.',
        keywords: ['pet', 'dog', 'cat', 'vet', 'swallowed'],
    },
    {
        id: 'partner-needs-help',
        category: 'family',
        variants: [
            "My partner's car broke down and I have to go rescue them.",
            "My spouse is having a crisis and I need to stay home and support them.",
            "Significant other got locked out of the house/car, I have to bring the spare key.",
            "My partner got severely sick, I'm playing nurse tonight.",
            "Family emergency involving my spouse, I have to drop everything.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Coworker', 'Boss'],
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.85,
        explanation: 'Shifts the emergency to someone else so you don\'t have to fake symptoms later.',
        keywords: ['partner', 'spouse', 'rescue', 'significant other', 'wife', 'husband'],
    },
    {
        id: 'family-visiting',
        category: 'family',
        variants: [
            "Out-of-town family just showed up at my door completely unannounced.",
            "My parents decided to surprise me with a visit this weekend.",
            "A relative is passing through town for one night only and insists on seeing me.",
            "Hosting unexpected family guests, I'm tied up all evening.",
            "My in-laws just dropped in. Send help, can't leave.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Lunch', 'Coffee'],
        noticeSuitability: ['Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.76,
        explanation: 'Relatable family friction that easily gets you out of social events.',
        keywords: ['family', 'visit', 'unannounced', 'parents', 'in-laws'],
    },

    // --- TRANSPORTATION & TRAVEL ---
    {
        id: 'car-breakdown',
        category: 'travel',
        variants: [
            "My car just broke down on the side of the highway. Waiting for a tow.",
            "Engine overheated and I'm stranded. Currently dealing with AAA.",
            "My car won't start. The battery is completely dead.",
            "Got a completely flat tire and the spare is missing/damaged.",
            "Check engine light is flashing red and the car is shaking. Can't drive it.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Party', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.86,
        explanation: 'A classic. Highly verifiable if you actually show up later without a car.',
        keywords: ['car', 'broke down', 'tire', 'AAA', 'battery', 'tow'],
    },
    {
        id: 'transit-failure',
        category: 'travel',
        variants: [
            "The train/subway is completely stalled underground. I'm stuck.",
            "Massive transit delays, all lines are suspended. I can't get there.",
            "The bus broke down and there isn't another one for an hour.",
            "Public transit is a nightmare today, massive signal failure.",
            "Someone pulled the emergency brake on the train. We are stopped indefinitely.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Party', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ALL_TONE,
        baseConfidence: 0.84,
        explanation: 'Best for city dwellers. Transit failures are unquestioned facts of life.',
        keywords: ['train', 'subway', 'transit', 'bus', 'stalled', 'delays'],
    },
    {
        id: 'traffic-nightmare',
        category: 'travel',
        variants: [
            "There's a massive accident on the highway. Traffic is at a complete standstill.",
            "I'm stuck in gridlock. GPS says it's adding 2 hours to my trip.",
            "Major road closures ahead of me, I'm completely boxed in.",
            "Traffic is literally not moving. I've been in the same spot for 30 minutes.",
            "A truck overturned on the interstate. I'm never going to make it.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ALL_TONE,
        baseConfidence: 0.82,
        explanation: 'Standard excuse. Easily verified via Google Maps, so use with caution.',
        keywords: ['traffic', 'accident', 'highway', 'gridlock', 'standstill'],
    },
    {
        id: 'travel-flight-delayed',
        category: 'travel',
        variants: [
            "My flight got severely delayed/cancelled. I'm stuck at the airport.",
            "Missed my connection due to a storm. Rebooked for tomorrow.",
            "I'm grounded in another city. Flight was cancelled due to crew timing out.",
            "Stuck on the tarmac for hours. I won't be landing anytime soon.",
            "Airline lost my luggage and I'm stuck at baggage claim filling out forms.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Meeting', 'Party', 'Dinner', 'Trip', 'Interview'],
        noticeSuitability: ['1 hour', 'Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.88,
        explanation: 'Only use if they know you are traveling. Airlines are notoriously unreliable.',
        keywords: ['flight', 'airport', 'cancelled', 'delayed', 'luggage'],
    },
    {
        id: 'car-accident',
        category: 'travel',
        variants: [
            "I was just in a minor fender bender. I'm okay, but waiting for the police/insurance.",
            "Someone rear-ended me. Dealing with the aftermath, but I'm unhurt.",
            "Car accident. Not my fault, but my car isn't drivable. Need to cancel.",
            "Just got sideswiped. I'm fine but exchanging information and waiting for a tow.",
            "Minor crash on the way there. Adrenaline is high, I need to go home.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.95,
        explanation: 'Nuclear option. Generates a lot of sympathy but requires a fake story later.',
        keywords: ['accident', 'fender bender', 'crash', 'rear-ended', 'police'],
    },

    // --- TECHNOLOGY ---
    {
        id: 'tech-internet-outage',
        category: 'technology',
        variants: [
            "My internet went down and my ISP says there's a neighborhood outage.",
            "Completely lost WiFi. I'm tethering right now to send this message.",
            "Router fried itself. Trying to work from a coffee shop but it's not viable.",
            "ISP is doing unannounced maintenance. I have absolutely no connection.",
            "My internet is cutting in and out, I can't hold a stable Zoom connection.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Client', 'Friend'],
        eventSuitability: ['Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal', 'Casual'],
        baseConfidence: 0.86,
        explanation: 'The ultimate WFH excuse. Untestable and highly common.',
        keywords: ['internet', 'outage', 'wifi', 'router', 'isp'],
    },
    {
        id: 'tech-computer-crash',
        category: 'technology',
        variants: [
            "My laptop just blue-screened and won't boot past the BIOS.",
            "Windows decided to force a multi-hour update right before our call.",
            "My computer completely died. Spilled coffee/water on it.",
            "Hard drive corrupted. I'm frantically trying to recover my files.",
            "Laptop is in a boot loop. Tech support is telling me it's bricked.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Client'],
        eventSuitability: ['Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal', 'Very apologetic'],
        baseConfidence: 0.83,
        explanation: 'Perfect for missing remote meetings. Fails if you need to email them a document.',
        keywords: ['laptop', 'computer', 'boot', 'update', 'died', 'blue-screen'],
    },
    {
        id: 'tech-phone-broke',
        category: 'technology',
        variants: [
            "I dropped my phone and the screen is completely shattered and unresponsive.",
            "My phone fell in water and is sitting in rice. Replying from my iPad/laptop.",
            "Phone battery swelled/died. I have no mobile communication right now.",
            "Lost my phone on the train/bus. Currently scrambling to track it.",
            "My phone was stolen. I'm locking down my accounts right now.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Family', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Party', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.78,
        explanation: 'Explains why you didn\'t text earlier or can\'t navigate to the location.',
        keywords: ['phone', 'shattered', 'screen', 'dropped', 'lost', 'stolen'],
    },
    {
        id: 'tech-power-outage',
        category: 'technology',
        variants: [
            "A transformer blew outside and we lost all power.",
            "Rolling blackouts just hit my block. No power, no internet.",
            "Tree fell on the power lines. PG&E says it'll be hours.",
            "Completely lost power at my house. Staring at the walls in the dark.",
            "Power outage fried my modem. Cannot get online.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Meeting', 'Interview', 'Party', 'Dinner'], // if hosting
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ALL_TONE,
        baseConfidence: 0.81,
        explanation: 'Believable, especially in summer/winter or during storms.',
        keywords: ['power', 'outage', 'blackout', 'transformer', 'dark'],
    },
    {
        id: 'tech-software-bug',
        category: 'technology',
        variants: [
            "My calendar app glitched and completely deleted this from my schedule.",
            "Zoom/Teams is forcing a reinstall and keeps crashing on launch.",
            "The link you sent is giving me a security error and I can't join.",
            "My 2FA app wiped my tokens and I'm locked out of my corporate accounts.",
            "VPN is completely down, I can't access any of the files we need.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Client'],
        eventSuitability: ['Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal', 'Very apologetic'],
        baseConfidence: 0.77,
        explanation: 'Corporate bureaucracy and bad software is always a valid excuse.',
        keywords: ['glitch', 'calendar', 'zoom', 'teams', 'vpn', '2fa'],
    },

    // --- PERSONAL & SCHEDULING ---
    {
        id: 'schedule-double-booked',
        category: 'scheduling',
        variants: [
            "I'm so incredibly sorry, I double-booked myself and the other commitment was made months ago.",
            "I completely messed up my calendar and double-booked tonight.",
            "I just realized I have two things scheduled at the exact same time.",
            "A massive scheduling oversight on my end—I already committed to something else today.",
            "I have an overlapping conflict that I cannot get out of.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date', 'Coworker'],
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['Today', 'Tomorrow', 'A few days', 'A week'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic', 'Professional'],
        baseConfidence: 0.76,
        explanation: 'Honest mistake. Best used with advance notice, terrible for 15-minute notice.',
        keywords: ['double-booked', 'calendar', 'oversight', 'conflict', 'overlapping'],
    },
    {
        id: 'schedule-wrong-time',
        category: 'scheduling',
        variants: [
            "I wrote this down for tomorrow, not today! I am so sorry.",
            "I got the time zones completely mixed up. I am nowhere near a computer.",
            "I thought we were meeting at 7, not 5. I'm still at work.",
            "Calendar app synced it to the wrong day. I am so embarrassed.",
            "I have the wrong date in my phone. I'm completely unprepared.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.71,
        explanation: 'Makes you look a bit disorganized, but gets you out of the immediate event.',
        keywords: ['time zone', 'wrong date', 'mixed up', 'calendar', 'tomorrow'],
    },
    {
        id: 'schedule-overslept',
        category: 'scheduling',
        variants: [
            "My alarm completely failed to go off. I just woke up in a panic.",
            "I slept through three alarms. I'm so incredibly sorry.",
            "Phone died overnight so my alarm didn't ring. Just woke up.",
            "I took a nap and accidentally slept for 4 hours. I missed it.",
            "Jet lag absolutely destroyed me. I just woke up and it's PM.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Coworker', 'Boss'],
        eventSuitability: ['Coffee', 'Meeting', 'Lunch'], // Morning/afternoon things
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.74,
        explanation: 'For morning meetings. It\'s embarrassing but happens to everyone.',
        keywords: ['alarm', 'overslept', 'woke up', 'slept through', 'nap'],
    },
    {
        id: 'personal-wardrobe',
        category: 'logistics',
        variants: [
            "I spilled coffee all over my only clean suit/shirt and have to go change.",
            "My dog peed on my outfit as I was walking out the door.",
            "Split my pants entirely open on the way there. Going home.",
            "Stepped in a massive puddle/mud. I am completely soaked.",
            "Bird pooped on my head. I have to go shower. Not my day.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.72,
        explanation: 'Funny, slightly humiliating, but undeniably effective for being late or cancelling.',
        keywords: ['spilled', 'pants', 'mud', 'soaked', 'outfit', 'bird'],
    },
    {
        id: 'personal-exhaustion',
        category: 'personal-space',
        variants: [
            "I didn't sleep a wink last night and am literally falling asleep standing up.",
            "I'm operating on 2 hours of sleep and wouldn't be good company.",
            "My insomnia was brutal last night. I need to catch up on sleep.",
            "I'm completely drained from the week. I need to stay in and recover.",
            "Physical exhaustion caught up to me. I'm going to pass out.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date'],
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Coffee'],
        noticeSuitability: ['1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.81,
        explanation: 'People respect physical exhaustion more than mental exhaustion sometimes.',
        keywords: ['sleep', 'insomnia', 'exhaustion', 'drained', 'tired'],
    },

    // --- FINANCIAL & LEGAL ---
    {
        id: 'financial-tight',
        category: 'financial',
        variants: [
            "Things are a bit tight financially right now, I need to pass on expensive dinners.",
            "I'm strictly budgeting this month and have to decline anything that costs money.",
            "I got hit with a huge unexpected bill and need to lay low.",
            "My wallet is hurting this week. Can we do something free instead next time?",
            "I'm trying to save money right now, so I'm skipping going out.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date'],
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Trip', 'Coffee', 'Lunch'],
        noticeSuitability: ['Today', 'Tomorrow', 'A few days', 'A week'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual'],
        baseConfidence: 0.75,
        explanation: 'Honest boundary setting. Friends will understand.',
        keywords: ['tight', 'budget', 'bill', 'save money', 'wallet', 'expensive'],
    },
    {
        id: 'financial-fraud',
        category: 'financial',
        variants: [
            "My bank just flagged a bunch of fraudulent charges. I'm on the phone with fraud prevention.",
            "Someone stole my credit card info. Dealing with the bank to lock everything down.",
            "My debit card got skimmed and my account is frozen. I have zero access to money.",
            "Identity theft issue just popped up. I'm spending the evening sorting it out.",
            "My wallet was stolen. I'm frantically cancelling all my cards.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Casual', 'Very apologetic'],
        baseConfidence: 0.87,
        explanation: 'High stress, high urgency. Nobody questions bank fraud.',
        keywords: ['fraud', 'stole', 'credit card', 'bank', 'frozen', 'stolen'],
    },
    {
        id: 'legal-jury',
        category: 'financial', // grouped as administrative/legal
        variants: [
            "I got selected for jury duty and they are sequestering us/it's running late.",
            "I'm stuck at the courthouse dealing with jury selection.",
            "Jury duty ran way over today. I'm mentally exhausted.",
            "I have to appear in court for a traffic ticket/minor issue tomorrow morning.",
            "Dealing with an urgent legal/notary document that has to be filed before 5.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Client', 'Friend', 'Best Friend'],
        eventSuitability: ['Meeting', 'Lunch', 'Coffee', 'Dinner', 'Interview'],
        noticeSuitability: ['Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal', 'Casual'],
        baseConfidence: 0.79,
        explanation: 'Civic duty is a powerful, unarguable excuse.',
        keywords: ['jury', 'courthouse', 'legal', 'ticket', 'notary'],
    },
    {
        id: 'admin-dmv',
        category: 'logistics',
        variants: [
            "I'm trapped at the DMV. It's been 3 hours and they haven't called my number.",
            "I have to go to the DMV to sort out a registration issue immediately.",
            "Stuck at the passport office trying to get an expedited renewal.",
            "Bureaucratic nightmare at City Hall. I am stuck in line.",
            "Dealing with an IRS/Tax issue on the phone. Been on hold for 2 hours.",
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Best Friend', 'Date'],
        eventSuitability: ['Meeting', 'Lunch', 'Coffee'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.80,
        explanation: 'Everyone hates the DMV. They will pity you.',
        keywords: ['dmv', 'passport', 'line', 'on hold', 'irs', 'city hall'],
    },

    // --- WEATHER & ACTS OF GOD ---
    {
        id: 'weather-snowed-in',
        category: 'weather',
        variants: [
            "I am completely snowed in. The plow hasn't hit my street yet.",
            "The roads are completely iced over, it's not safe to drive.",
            "Blizzard conditions out my window. I'm not risking it.",
            "Car is buried under 2 feet of snow. I can't dig it out in time.",
            "Local authorities issued a travel ban due to the snowstorm.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.90,
        explanation: 'Only use in winter in appropriate climates. 100% effective.',
        keywords: ['snow', 'ice', 'blizzard', 'plow', 'winter'],
    },
    {
        id: 'weather-flooding',
        category: 'weather',
        variants: [
            "The roads around my house are completely flooded. I'm trapped.",
            "Flash flood warning in my area. They are advising everyone to stay off the roads.",
            "My basement is taking on water from the storm, I have to pump it out.",
            "Torrential downpour makes visibility zero. I turned the car around.",
            "Tree came down in the storm and blocked my driveway.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.88,
        explanation: 'Good for severe thunderstorms/hurricanes.',
        keywords: ['flood', 'storm', 'downpour', 'tree', 'weather'],
    },
    {
        id: 'weather-heatwave',
        category: 'weather',
        variants: [
            "My AC broke in the middle of this heatwave. I am trying to fix it before my pets melt.",
            "It's 110 degrees and my car's AC is busted. I can't drive in this.",
            "Rolling blackouts due to the heatwave. I have to stay and monitor the house.",
            "I got slight heatstroke earlier and feel terribly nauseous.",
            "It's dangerously hot outside and I'd rather stay in the AC.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date'],
        eventSuitability: ['Coffee', 'Lunch', 'Party', 'Trip'], // Daytime/outdoor events
        noticeSuitability: ['Today', 'Tomorrow'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual'],
        baseConfidence: 0.70,
        explanation: 'Good for getting out of outdoor summer activities.',
        keywords: ['heat', 'heatwave', 'ac', 'melt', 'heatstroke'],
    },

    // --- MISCELLANEOUS / FUNNY / WEIRD ---
    {
        id: 'misc-stuck-elevator',
        category: 'logistics',
        variants: [
            "I am literally trapped in an elevator right now. Waiting for the fire department.",
            "The elevator in my building broke down while I was in it.",
            "Stuck in the lift. Maintenance says it'll be 45 minutes.",
            "Got stuck in the elevator on my way out. I'm panicking slightly.",
            "Elevator jammed between floors. Send help and start without me.",
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.92,
        explanation: 'Extremely specific and short-term. Great for being 1 hour late.',
        keywords: ['elevator', 'trapped', 'stuck', 'lift', 'maintenance'],
    },
    {
        id: 'misc-neighbor-dispute',
        category: 'logistics',
        variants: [
            "My upstairs neighbor's tub overflowed into my apartment. Dealing with it.",
            "Next door neighbor is having a domestic dispute and the police are knocking on doors.",
            "Neighbor hit my parked car. Currently exchanging insurance.",
            "My crazy neighbor is blocking my driveway and refuses to move.",
            "Dealing with a very aggressive neighbor dispute over property lines.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Coworker', 'Date'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Party', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.81,
        explanation: 'Blames another unpredictable human. Highly entertaining excuse.',
        keywords: ['neighbor', 'dispute', 'police', 'driveway', 'upstairs'],
    },
    {
        id: 'misc-food-delivery-ruined',
        category: 'logistics',
        variants: [
            "My grocery delivery driver dropped all my groceries in a puddle. Cleaning up.",
            "A delivery driver hit my mailbox/fence and drove off.",
            "Someone stole my massive meal prep delivery box. Filing a report.",
            "Waiting for a replacement because Doordash delivered to the wrong house.",
            "Spilled a 2-liter of oil/soda all over my kitchen floor. I am scrubbing.",
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual'],
        toneSuitability: ['Casual'],
        baseConfidence: 0.65,
        explanation: 'Low stakes, mostly just annoying. Good for casual ditching.',
        keywords: ['delivery', 'driver', 'grocery', 'spilled', 'cleaning'],
    },
    
    // --- ADDITIONAL TEMPLATES (27-51) ---
    {
        id: 'medical-pink-eye',
        category: 'illness',
        variants: [
            "I woke up with severe pink eye and it's highly contagious.",
            "My eye is swollen shut with an infection. I can't be around people.",
            "I have a terrible eye infection and need to keep it compressed.",
            "Looks like I caught conjunctivitis. I have to isolate.",
            "My eyes are incredibly red and weeping. Pretty sure it's pink eye."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.91,
        explanation: 'Pink eye is visually horrifying and extremely contagious. Perfect excuse.',
        keywords: ['pink eye', 'infection', 'eye', 'contagious', 'conjunctivitis']
    },
    {
        id: 'medical-vertigo',
        category: 'illness',
        variants: [
            "I'm experiencing severe vertigo and the room won't stop spinning.",
            "I stood up and got hit with extreme dizziness. I have to lie down.",
            "An inner ear issue is giving me horrible vertigo right now.",
            "I'm too dizzy to stand up, let alone drive anywhere.",
            "Sudden onset vertigo. I feel like I'm on a boat in a storm."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ALL_TONE,
        baseConfidence: 0.88,
        explanation: 'Vertigo is sudden and completely immobilizing.',
        keywords: ['vertigo', 'dizzy', 'spinning', 'inner ear', 'stand up']
    },
    {
        id: 'medical-lost-voice',
        category: 'illness',
        variants: [
            "I've completely lost my voice. I sound like a frog.",
            "Laryngitis hit me hard. I can only whisper right now.",
            "My throat is raw and I can't speak above a whisper.",
            "I woke up with no voice whatsoever. Literally cannot talk.",
            "My vocal cords are inflamed. Doctor said total vocal rest."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview', 'Party'],
        noticeSuitability: ['Today', 'Tomorrow'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.85,
        explanation: 'Excellent for getting out of phone calls or loud social events.',
        keywords: ['voice', 'laryngitis', 'whisper', 'throat', 'speak']
    },
    {
        id: 'pet-chocolate',
        category: 'family',
        variants: [
            "My dog just ate chocolate and I have to induce vomiting.",
            "The dog got into something toxic. Rushing to the emergency vet.",
            "My pet ate a foreign object and is choking/gagging.",
            "Dog ate grapes/onions. I'm frantically calling poison control.",
            "My puppy chewed through a wire. Dealing with the aftermath."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.94,
        explanation: 'High adrenaline emergency that nobody will question.',
        keywords: ['dog', 'chocolate', 'toxic', 'vomiting', 'poison']
    },
    {
        id: 'home-gas-leak',
        category: 'logistics',
        variants: [
            "I smell gas in my house. I'm waiting outside for the utility company.",
            "Carbon monoxide alarm went off. The fire department is here.",
            "Evacuated the apartment building due to a suspected gas leak.",
            "Gas company shut off our line due to a leak. It's freezing.",
            "We have a suspected gas leak and are trapped outside."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Formal', 'Very apologetic'],
        baseConfidence: 0.97,
        explanation: 'Life-threatening emergency. A literal "drop everything" excuse.',
        keywords: ['gas', 'leak', 'smell', 'carbon monoxide', 'evacuated']
    },
    {
        id: 'home-roof-leak',
        category: 'logistics',
        variants: [
            "My roof is actively leaking onto my bed/laptop.",
            "Heavy rain caused a massive leak in my ceiling. Scrambling with buckets.",
            "Water is pouring through my light fixtures. Landlord is en route.",
            "Ceiling just partially collapsed from water damage.",
            "Skylight shattered/leaking. I am dealing with a huge mess."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ALL_TONE,
        baseConfidence: 0.92,
        explanation: 'Property damage is universally accepted as a reason to stay home.',
        keywords: ['roof', 'leak', 'ceiling', 'water', 'buckets']
    },
    {
        id: 'car-parked-in',
        category: 'travel',
        variants: [
            "Someone parked inches from my bumper and I am completely boxed in.",
            "My neighbor's guests blocked my driveway and they aren't answering the door.",
            "I'm blocked in by a moving truck and they refuse to move for another hour.",
            "A delivery truck is idling behind my car and the driver disappeared.",
            "Someone double parked next to me and I literally cannot leave my spot."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Meeting', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic', 'Professional'],
        baseConfidence: 0.86,
        explanation: 'Infuriating and out of your control. Generates sympathy.',
        keywords: ['blocked', 'driveway', 'parked in', 'moving truck', 'double parked']
    },
    {
        id: 'car-towed',
        category: 'travel',
        variants: [
            "My car got towed. I am furious and have to go to the impound lot.",
            "Walked outside and my car is gone. Turns out it was towed.",
            "I parked in a tow zone by mistake. Currently stranded and angry.",
            "Car got booted/towed. I have to spend the next 3 hours fixing this.",
            "My vehicle was towed from my own spot. Dealing with management."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Casual', 'Very apologetic', 'Professional'],
        baseConfidence: 0.90,
        explanation: 'An expensive, day-ruining event. No one expects you to show up after this.',
        keywords: ['towed', 'impound', 'booted', 'stranded', 'car']
    },
    {
        id: 'social-friend-crisis',
        category: 'personal-space',
        variants: [
            "A close friend is going through a terrible breakup and needs me right now.",
            "My best friend just had a crisis and I need to go support them.",
            "A friend called me crying. I have to go be with them.",
            "I'm dealing with a friend's emergency right now. Can't step away.",
            "Playing therapist for a friend in crisis tonight."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Party', 'Movie', 'Dinner', 'Coffee', 'Lunch'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.82,
        explanation: 'Shows you are a loyal person while getting you out of plans.',
        keywords: ['friend', 'crisis', 'breakup', 'crying', 'support']
    },
    {
        id: 'work-deployment-failed',
        category: 'professional-urgent',
        variants: [
            "Our software deployment just failed spectacularly. Rollback in progress.",
            "Pushed code to production and it broke everything. I'm stuck here.",
            "Massive bug found in production. Dev team is in war room mode.",
            "The release went terribly wrong. I have to stay and fix it.",
            "Database migration failed. I'm going to be working until 3 AM."
        ],
        relationshipSuitability: ['Coworker', 'Boss', 'Friend', 'Best Friend', 'Date'],
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.89,
        explanation: 'Very specific to software/IT, but highly effective.',
        keywords: ['deployment', 'production', 'rollback', 'bug', 'release']
    },
    {
        id: 'work-hr-issue',
        category: 'professional-urgent',
        variants: [
            "I got pulled into a sudden, mandatory HR meeting.",
            "Dealing with an urgent personnel issue that requires immediate attention.",
            "A sensitive employee issue came up. I'm stuck behind closed doors.",
            "HR needs my statement on an incident immediately.",
            "Dealing with an unexpected compliance violation at work."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Date'],
        eventSuitability: ['Meeting', 'Coffee', 'Lunch', 'Interview'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal'],
        baseConfidence: 0.84,
        explanation: 'Ominous and unquestionable. People don\'t pry into HR issues.',
        keywords: ['hr', 'personnel', 'sensitive', 'meeting', 'compliance']
    },
    {
        id: 'misc-lost-wallet',
        category: 'logistics',
        variants: [
            "I lost my wallet and have no ID, credit cards, or cash.",
            "My wallet is missing. I'm retracing my steps frantically.",
            "Left my wallet in an Uber. Trying to contact the driver.",
            "I literally cannot pay for anything right now, wallet is gone.",
            "Lost my purse/wallet. Spending the evening cancelling cards."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker', 'Family'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Party', 'Trip'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.81,
        explanation: 'Creates a logistical nightmare that prevents you from going out.',
        keywords: ['wallet', 'purse', 'lost', 'uber', 'cash']
    },
    {
        id: 'home-pest-control',
        category: 'logistics',
        variants: [
            "I just found a massive pest infestation (bed bugs/roaches) and am freaking out.",
            "Found mice in my kitchen. Waiting on the emergency exterminator.",
            "A bat got into my house. Currently hiding in the bathroom.",
            "Wasp nest inside my walls just broke through. Exterminator is here.",
            "Massive ant invasion. I'm scrubbing the entire house down with bleach."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Family', 'Date', 'Coworker'],
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Coffee', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.83,
        explanation: 'Disgusting and urgent. Nobody will want to come over either.',
        keywords: ['pest', 'exterminator', 'mice', 'bugs', 'infestation']
    },
    {
        id: 'car-pulled-over',
        category: 'travel',
        variants: [
            "I got pulled over by the police and it's taking forever.",
            "Currently sitting on the side of the road with a cop behind me.",
            "Got stopped for a broken taillight. Going to be late.",
            "Dealing with a traffic ticket right now. Completely threw off my timing.",
            "Police checkpoint slowing everything down. Stuck in line."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Client', 'Friend', 'Date'],
        eventSuitability: ['Meeting', 'Interview', 'Coffee', 'Lunch', 'Dinner'],
        noticeSuitability: ['15 minutes'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic', 'Professional'],
        baseConfidence: 0.86,
        explanation: 'Perfect for being 15-30 minutes late.',
        keywords: ['pulled over', 'police', 'cop', 'ticket', 'taillight']
    },
    {
        id: 'family-spilled-coffee',
        category: 'logistics',
        variants: [
            "My kid spilled an entire cup of coffee on my laptop.",
            "I just knocked a full glass of water onto my work computer.",
            "Massive spill in the kitchen. Glass everywhere. Cleaning it up.",
            "My toddler threw up on my only clean outfit.",
            "Spilled bleach/paint on the carpet. Frantically trying to clean it."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker', 'Boss'],
        eventSuitability: ['Meeting', 'Coffee', 'Lunch'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.77,
        explanation: 'A messy, immediate problem that requires your full attention.',
        keywords: ['spilled', 'coffee', 'laptop', 'cleaning', 'glass']
    },
    {
        id: 'medical-allergic-food',
        category: 'illness',
        variants: [
            "I accidentally ate something I'm allergic to. Going to urgent care.",
            "Cross-contamination issue with my lunch. My throat feels tight.",
            "Used my EpiPen. Heading to the ER just to be safe.",
            "Severe allergic reaction to a new medication.",
            "Ate a bad batch of shellfish. Face is swelling up."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ALL_IMPORTANCE,
        toneSuitability: ['Professional', 'Formal', 'Very apologetic', 'Casual'],
        baseConfidence: 0.95,
        explanation: 'Life or death situation. Utterly unquestionable.',
        keywords: ['allergic', 'epipen', 'urgent care', 'throat', 'reaction']
    },
    {
        id: 'home-tree-fell',
        category: 'logistics',
        variants: [
            "A massive branch fell on my car/driveway. Assessing the damage.",
            "Tree came down in my yard and took out the power line.",
            "Neighbor's tree crashed through my fence. Dealing with insurance.",
            "Storm blew a tree down across my street. We are boxed in.",
            "Huge limb fell on the roof. Waiting for a structural engineer."
        ],
        relationshipSuitability: ALL_RELATIONSHIPS,
        eventSuitability: ALL_EVENTS,
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.89,
        explanation: 'Requires recent bad weather to be believable.',
        keywords: ['tree', 'branch', 'fell', 'roof', 'fence']
    },
    {
        id: 'tech-hacked',
        category: 'technology',
        variants: [
            "My email/bank account got hacked. I'm spending the day changing passwords.",
            "Victim of identity theft today. Locking down all my credit.",
            "Someone hijacked my social media accounts. Dealing with support.",
            "My computer got ransomware. I am panicking and talking to IT.",
            "Got phished and clicked a bad link. Corporate IT is wiping my laptop."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Family'],
        eventSuitability: ['Meeting', 'Coffee', 'Lunch', 'Party'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional'],
        baseConfidence: 0.82,
        explanation: 'Modern nightmare scenario. Very relatable.',
        keywords: ['hacked', 'passwords', 'stolen', 'identity theft', 'phished']
    },
    {
        id: 'social-pet-sitter',
        category: 'family',
        variants: [
            "My dog walker/sitter flaked and I have to go let the dogs out.",
            "Pet sitter cancelled last minute. I can't leave the animals alone.",
            "I have to go administer medication to my cat at a very specific time.",
            "My dog has terrible separation anxiety today, I can't leave them.",
            "Got a noise complaint from my landlord about my dog barking. Have to go home."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Dinner', 'Party', 'Movie', 'Trip'],
        noticeSuitability: ['1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.79,
        explanation: 'Great for cutting an evening short.',
        keywords: ['sitter', 'dog', 'cat', 'medication', 'anxiety']
    },
    {
        id: 'work-investor-call',
        category: 'professional-urgent',
        variants: [
            "Got pulled into an impromptu meeting with the investors/board.",
            "VCs just asked for a massive data pull by EOD.",
            "Board members are asking questions and my boss needs me to crunch numbers.",
            "Emergency pitch deck revisions. I'm stuck here.",
            "Investors are touring the office. All hands on deck."
        ],
        relationshipSuitability: ['Friend', 'Date', 'Family'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie'],
        noticeSuitability: ['15 minutes', '1 hour', 'Today'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.84,
        explanation: 'High prestige excuse. Sounds impressive and unavoidable.',
        keywords: ['investor', 'board', 'vcs', 'pitch deck', 'crunch numbers']
    },
    {
        id: 'logistics-contact-lenses',
        category: 'logistics',
        variants: [
            "I ripped my last pair of contact lenses and my glasses are broken.",
            "I literally cannot see. Lost my glasses and I'm legally blind without them.",
            "My contact got stuck behind my eye. Having a minor medical panic.",
            "Sat on my glasses. I am severely visually impaired right now.",
            "Dropped my contact down the sink. I have a raging headache from one eye."
        ],
        relationshipSuitability: ['Friend', 'Best Friend', 'Date', 'Coworker'],
        eventSuitability: ['Coffee', 'Lunch', 'Dinner', 'Movie', 'Meeting'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.73,
        explanation: 'Quirky but completely paralyzing if you have bad vision.',
        keywords: ['contact lenses', 'glasses', 'blind', 'ripped', 'eye']
    },
    {
        id: 'home-garage-door',
        category: 'logistics',
        variants: [
            "My garage door spring snapped and I literally cannot get my car out.",
            "Garage door motor died and my car is trapped inside.",
            "Power outage means I can't open my electronic gate.",
            "The gate to my apartment complex is broken and stuck closed.",
            "My car is trapped in the parking structure due to a broken arm."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Date', 'Client'],
        eventSuitability: ['Meeting', 'Interview', 'Coffee', 'Lunch', 'Dinner'],
        noticeSuitability: ['15 minutes', '1 hour'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Casual', 'Professional', 'Very apologetic'],
        baseConfidence: 0.86,
        explanation: 'Highly specific mechanical failure that prevents travel.',
        keywords: ['garage', 'door', 'trapped', 'spring', 'gate']
    },
    {
        id: 'misc-jury-sequestered',
        category: 'financial', // Using existing legal category
        variants: [
            "I am stuck in the jury deliberation room. We haven't reached a verdict.",
            "The judge is running 3 hours behind schedule. Still at the courthouse.",
            "Selected for a grand jury and it's a massive time commitment.",
            "I'm sequestered for a trial right now. Limited phone access.",
            "Jury duty ran incredibly late. I'm completely wiped out."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Client', 'Date'],
        eventSuitability: ['Meeting', 'Interview', 'Coffee', 'Lunch', 'Dinner'],
        noticeSuitability: ['Today', 'Tomorrow', 'A few days'],
        importanceSuitability: ['Casual', 'Planned', 'Important'],
        toneSuitability: ['Professional', 'Formal', 'Casual'],
        baseConfidence: 0.88,
        explanation: 'Legally mandated absence. Unarguable.',
        keywords: ['jury', 'verdict', 'judge', 'courthouse', 'sequestered']
    },
    {
        id: 'personal-mental-exhaustion',
        category: 'personal-space',
        variants: [
            "I've hit extreme introvert burnout. I need to recharge alone.",
            "My social battery is completely in the red. I have to stay home.",
            "I've been in back-to-back social events all week. I need a night off.",
            "I'm feeling incredibly overstimulated today. Need quiet time.",
            "I just want to be alone with my thoughts tonight. I'm sorry."
        ],
        relationshipSuitability: ['Best Friend', 'Friend', 'Family'],
        eventSuitability: ['Party', 'Dinner', 'Movie', 'Coffee'],
        noticeSuitability: ['1 hour', 'Today'],
        importanceSuitability: ['Casual'],
        toneSuitability: ['Casual', 'Very apologetic'],
        baseConfidence: 0.82,
        explanation: 'Honest and modern. Gen Z/Millennials respect social battery boundaries.',
        keywords: ['social battery', 'introvert', 'burnout', 'recharge', 'overstimulated']
    },
    {
        id: 'travel-lost-passport',
        category: 'travel',
        variants: [
            "I cannot find my passport anywhere and my flight is tomorrow.",
            "My ID/Driver's License is missing. I can't get through TSA.",
            "I accidentally packed my car keys in my checked luggage.",
            "I am at the airport and realized I booked the flight for the wrong month.",
            "TSA line is 3 hours long. I am definitely missing this flight."
        ],
        relationshipSuitability: ['Boss', 'Coworker', 'Friend', 'Family'],
        eventSuitability: ['Trip', 'Meeting', 'Party'], // Travel-heavy events
        noticeSuitability: ['1 hour', 'Today', 'Tomorrow'],
        importanceSuitability: ['Planned', 'Important', 'Very Important'],
        toneSuitability: ['Professional', 'Casual', 'Very apologetic'],
        baseConfidence: 0.85,
        explanation: 'Massive travel disasters that completely derail plans.',
        keywords: ['passport', 'tsa', 'luggage', 'airport', 'id']
    }
];

export const relationshipOptions: RelationKey[] = [
    'Friend',
    'Best Friend',
    'Family',
    'Date',
    'Coworker',
    'Boss',
    'Client',
    'Other',
];

export const closenessOptions: ClosenessKey[] = [
    'Stranger',
    'Acquaintance',
    'Friend',
    'Close Friend',
    'Best Friend',
    'Family',
];

export const eventOptions: EventKey[] = [
    'Coffee',
    'Lunch',
    'Dinner',
    'Movie',
    'Birthday',
    'Party',
    'Meeting',
    'Trip',
    'Interview',
    'Other',
];

export const importanceOptions: ImportanceKey[] = ['Casual', 'Planned', 'Important', 'Very Important'];
export const noticeOptions: NoticeKey[] = ['15 minutes', '1 hour', 'Today', 'Tomorrow', 'A few days', 'A week'];
export const toneOptions: ToneKey[] = ['Casual', 'Professional', 'Formal', 'Very apologetic'];
