import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
    shell: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        maxWidth: '100%',
        height: '100%',
        gap: 16,
        padding: 20,
        background: 'linear-gradient(135deg, #f8fbff 0%, #eef4ff 100%)',
        color: '#1f2937',
        overflow: 'auto',
        boxSizing: 'border-box',
        cursor: 'default',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
    },
    eyebrow: {
        fontSize: 11,
        textTransform: 'uppercase',
        letterSpacing: '0.24em',
        color: '#5b6b86',
        marginBottom: 4,
    },
    title: {
        margin: 0,
        textAlign: 'center',
        fontSize: 24,
        color: '#111827',
    },
    badge: {
        padding: '8px 12px',
        borderRadius: 999,
        background: '#dbeafe',
        color: '#1d4ed8',
        fontSize: 12,
        fontWeight: 700,
    },
    layout: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        maxWidth: '100%',
        gap: 16,
        boxSizing: 'border-box',
    },
    card: {
        width: '100%',
        maxWidth: '100%',
        boxSizing: 'border-box',
        background: 'rgba(255,255,255,0.82)',
        border: '1px solid #dbe4f0',
        borderRadius: 16,
        padding: 16,
        boxShadow: '0 12px 34px rgba(15, 23, 42, 0.08)',
        backdropFilter: 'blur(10px)',
    },
    grid: {
        display: 'grid',
        width: '100%',
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
        gap: 12,
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: 6,
        marginBottom: 12,
    },
    label: {
        fontWeight: 700,
        fontSize: 14,
        color: '#374151',
        fontFamily: 'MillenniumBold, "Times New Roman", Times, serif',
    },
    input: {
        padding: '10px 12px',
        borderRadius: 10,
        border: '1px solid #cbd5e1',
        background: '#fff',
        color: '#111827',
        fontFamily: 'Millennium, "Times New Roman", Times, serif',
        fontSize: 15,
        lineHeight: 1.4,
        cursor: 'text',
    },
    textarea: {
        padding: '10px 12px',
        borderRadius: 10,
        border: '1px solid #cbd5e1',
        background: '#fff',
        minHeight: 96,
        resize: 'vertical',
        color: '#111827',
        fontFamily: 'Millennium, "Times New Roman", Times, serif',
        fontSize: 15,
        lineHeight: 1.4,
        cursor: 'text',
    },
    inlineRow: {
        display: 'flex',
        width: '100%',
        gap: 8,
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    chipRow: {
        display: 'flex',
        gap: 8,
        flexWrap: 'wrap',
        marginTop: 8,
    },
    chip: {
        display: 'inline-flex',
        alignItems: 'center',
        background: '#eff6ff',
        color: '#1d4ed8',
        borderRadius: 999,
        padding: '6px 10px',
        fontSize: 12,
        gap: 6,
    },
    chipButton: {
        border: 'none',
        background: 'transparent',
        color: '#1d4ed8',
        cursor: 'pointer',
        fontSize: 14,
        padding: 0,
    },
    actions: {
        display: 'flex',
        justifyContent: 'flex-start',
        marginTop: 6,
    },
    primaryButton: {
        border: 'none',
        borderRadius: 999,
        padding: '10px 14px',
        background: '#2563eb',
        color: '#fff',
        cursor: 'pointer',
        fontWeight: 700,
        fontFamily: 'MillenniumBold, "Times New Roman", Times, serif',
        fontSize: 14,
    },
    secondaryButton: {
        border: '1px solid #cbd5e1',
        borderRadius: 999,
        padding: '8px 12px',
        background: '#fff',
        color: '#111827',
        cursor: 'pointer',
        fontWeight: 600,
        fontFamily: 'Millennium, "Times New Roman", Times, serif',
        fontSize: 14,
    },
    resultsHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    resultsTitle: {
        margin: 0,
        fontSize: 16,
        color: '#111827',
    },
    resultsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: 12,
        width: '100%',
    },
    resultCard: {
        width: '100%',
        boxSizing: 'border-box',
        padding: 12,
        borderRadius: 12,
        border: '1px solid #e2e8f0',
        background: '#fff',
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
    },
    resultTopRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 8,
        width: '100%',
    },
    resultText: {
        flex: 1,
        lineHeight: 1.4,
        cursor: 'pointer',
        userSelect: 'text',
        fontFamily: 'Millennium, "Times New Roman", Times, serif',
        fontSize: 15,
    },
    scorePill: {
        background: '#dcfce7',
        color: '#166534',
        borderRadius: 999,
        padding: '4px 8px',
        fontSize: 11,
        fontWeight: 700,
        whiteSpace: 'nowrap',
    },
    mutedText: {
        fontSize: 13,
        color: '#475569',
        lineHeight: 1.45,
        fontFamily: 'Millennium, "Times New Roman", Times, serif',
    },
    categoryTag: {
        alignSelf: 'flex-start',
        fontSize: 11,
        textTransform: 'capitalize',
        color: '#5b6b86',
        background: '#f1f5f9',
        borderRadius: 999,
        padding: '3px 8px',
    },
    resultBottomRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
        flexWrap: 'wrap',
        width: '100%',
    },
    moreButtonRow: {
        display: 'flex',
        justifyContent: 'flex-start',
        marginTop: 12,
    },
    linkButton: {
        border: 'none',
        background: 'transparent',
        color: '#2563eb',
        cursor: 'pointer',
        fontWeight: 700,
        padding: 0,
        alignSelf: 'flex-start',
        fontFamily: 'MillenniumBold, "Times New Roman", Times, serif',
        fontSize: 14,
    },
};
